version: '3.7'
services:
  finance_service:
    image: ${TAG}
    restart: always
    ports:
      - ${PORT}:${PORT}
      - 40010:40010
    security_opt:
      - seccomp:unconfined
    environment:
      - PORT=${PORT}
      - APP_MODE=docker
      - FINANCE_PAYMENT_SCHEDULER_TIME_UNIT=minute
      - FINANCE_PAYMENT_SCHEDULER_STATES=PAYMENT_PROCESS:60;PAYMENT_TRACKING:15
      - FINANCE_PAYMENT_SCHEDULER_INTERVAL=60
      - FINANCE_PAYMENT_SCHEDULER_PARENT_WORKER_TIMEOUT=25
      - FINANCE_PAYMENT_SCHEDULER_WORKER_TIMEOUT=20

      - FINANCE_ORDER_SCHEDULER_TIME_UNIT=minute
      - FINANCE_ORDER_SCHEDULER_INTERVAL=60
      - FINANCE_ORDER_SCHEDULER_PARENT_WORKER_TIMEOUT=25
      - FINANCE_ORDER_SCHEDULER_WORKER_TIMEOUT=20
      - FINANCE_ORDER_SCHEDULER_UPDATE_FINANCE_DURATION=true
      - FINANCE_ORDER_SCHEDULER_HANDLE_MISSED_FIRE_TIRGGER=true

      - FINANCE_SELLER_FINANCE_PREVENT_DUPLICATE_ORDER_ITEM=true

      - FINANCE_SELLER_FINANCE_TRIGGER_NAME=OST1-24h
      - FINANCE_SELLER_FINANCE_TRIGGER_TIME_UNIT=hour
      - FINANCE_SELLER_FINANCE_TRIGGER_INTERVAL=24
      - FINANCE_SELLER_FINANCE_TRIGGER_DURATION=24
      - FINANCE_SELLER_FINANCE_TRIGGER_POINT=23:59
      - FINANCE_SELLER_FINANCE_TRIGGER_POINT_TYPE=absolute
      - FINANCE_SELLER_FINANCE_TRIGGER_ENABLED=true
      - FINANCE_SELLER_FINANCE_TRIGGER_TEST_MODE=true

      - FINANCE_SERVICE_MONGO_HOST=mongo
      - FINANCE_SERVICE_MONGO_PORT=27017
      - FINANCE_SERVICE_MONGO_USER=root
      - FINANCE_SERVICE_MONGO_DB_NAME=financeService
      - FINANCE_SERVICE_MONGO_SELLER_COLLECTION_NAME=sellerFinance
      - FINANCE_SERVICE_MONGO_FINANCE_TRIGGER_COLLECTION_NAME=financeTrigger
      - FINANCE_SERVICE_MONGO_TRIGGER_HISTORY_COLLECTION_NAME=triggerHistory
      - FINANCE_SERVICE_MONGO_CONN_TIMEOUT=5
      - FINANCE_SERVICE_MONGO_READ_TIMEOUT=5
      - FINANCE_SERVICE_MONGO_WRITE_TIMEOUT=5
      - FINANCE_SERVICE_MONGO_MAX_CONN_IDLE_TIME=60
      - FINANCE_SERVICE_MONGO_MAX_POOL_SIZE=128
      - FINANCE_SERVICE_MONGO_MIN_POOL_SIZE=64
      - FINANCE_SERVICE_MONGO_WRITE_CONCERN_W=majority
      - FINANCE_SERVICE_MONGO_WRITE_CONCERN_J=true
      - FINANCE_SERVICE_MONGO_RETRY_WRITE=false

      - PROMETHEUS_PORT=9100

      - USER_SERVICE_ADDRESS=userservice
      - USER_SERVICE_PORT=9096

      - ORDER_SERVICE_ADDRESS=orderservice
      - ORDER_SERVICE_PORT=9095

      - PAYMENT_TRANSFER_SERVICE_ADDRESS=payemntTransferService
      - PAYMENT_TRANSFER_SERVICE_PORT=9793
    depends_on:
      - mongo

  mongo:
    image: registry.faza.io/mongo:4.2.2
    ports:
      - 27017:27017

  mongo-express:
    image: registry.faza.io/mongo-express:0.49
    ports:
      - 8081:8081
