version: '3.7'
services:
  finance-service:
    image: ${TAG}
    restart: always
    ports:
      - ${PORT}:${PORT}
      - 40000:40000
    security_opt:
      - seccomp:unconfined
    environment:
      - PORT=${PORT}
    env_file:
      - src/.env
    depends_on:
      - mongo
#      - mongo2
#      - mongo3
      - userservice
#      - orderservice
#      - paymentservice

  userservice:
    image: registry.faza.io/user-app/user-app:staging
    ports:
      - 9096:9096
    security_opt:
      - seccomp:unconfined
    environment:
      - PORT=9096
      - APP_MODE=grpc-server
      - APP_ENV=dev
      - APP_LOCALE=fa_IR
      - APP_COUNTRY=IR
      - APP_USER_REGISTRATION_DEFAULT_REQ=phone
      - APP_LANG_DIR=/app/resources/lang
      - APP_GEO_NAME_DIR=/app/resources/geonames
      - AUTH_DISABLE_LOGIN_ATTEMPT_STORAGE=false
      - AUTH_ACCESS_TOKEN_TTL=3000
      - AUTH_REFRESH_TOKEN_TTL=3600
      - VERIFY_TTL=600
      - VERIFY_REQUEST_MAX_ATTEMPTS=5
      - VERIFY_FINISH_ATTEMPTS=5
      - MONGO_USER=
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_CONN_TIMEOUT=100
      - MONGO_READ_TIMEOUT=5
      - MONGO_WRITE_TIMEOUT=5
      - READI_SINGLE_INSTANCE=true
      - REDIS_READ_HOST=redis
      - REDIS_READ_PORT=6379
      - REDIS_READ_DB=0
      - REDIS_READ_PASSWORD=
      - REDIS_WRITE_HOST=redis
      - REDIS_WRITE_PORT=6379
      - REDIS_WRITE_DB=0
      - REDIS_WRITE_PASSWORD=
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
    depends_on:
      - mongo
      - redis

#  orderservice:
#    image: registry.faza.io/order-service/order-service:staging
#    restart: always
#    ports:
#      - 9095:9095
#    security_opt:
#      - seccomp:unconfined
#    environment:
#      - PORT=9095
#      - APP_MODE=docker
#      - ORDER_SERVICE_MODE=server
#      - ORDER_SERVER_ADDRESS=
#      - ORDER_SERVER_PORT=9095
#      - ORDER_SERVICE_MONGO_HOST=mongo
#      - ORDER_SERVICE_MONGO_PORT=27017
#      - ORDER_SERVICE_MONGO_USER=root
#      - ORDER_SERVICE_MONGO_CONN_TIMEOUT=5
#      - ORDER_SERVICE_MONGO_READ_TIMEOUT=5
#      - ORDER_SERVICE_MONGO_WRITE_TIMEOUT=5
#      - ORDER_SERVICE_MONGO_MAX_CONN_IDLE_TIME=60
#      - ORDER_SERVICE_MONGO_MAX_POOL_SIZE=128
#      - ORDER_SERVICE_MONGO_MIN_POOL_SIZE=64
#      - ORDER_SERVICE_MONGO_DB_NAME=orderService
#      - ORDER_SERVICE_MONGO_COLLECTION_NAME=orders
#      - ORDER_SCHEDULER_TIME_UNIT=minute
#      - ORDER_SCHEDULER_STATES=Payment_Pending;Approval_Pending;Shipment_Pending;Shipment_Delayed;Shipped;Delivery_Pending;Delivered;Return_Shipment_Pending;Return_Shipped;Return_Delivered
#      - ORDER_SCHEDULER_INTERVAL=60
#      - ORDER_SCHEDULER_PARENT_WORKER_TIMEOUT=25
#      - ORDER_SCHEDULER_WORKER_TIMEOUT=20
#      - ORDER_SCHEDULER_STATE_TIME_UNIT=hour
#      - ORDER_SCHEDULER_SELLER_REACTION_TIME=10
#      - ORDER_SCHEDULER_PAYMENT_PENDING_STATE=15
#      - ORDER_SCHEDULER_RETRY_PAYMENT_PENDING_STATE=100
#      - ORDER_SCHEDULER_APPROVAL_PENDING_STATE=24
#      - ORDER_SCHEDULER_SHIPMENT_PENDING_STATE=80
#      - ORDER_SCHEDULER_SHIPPED_STATE=72
#      - ORDER_SCHEDULER_DELIVERY_PENDING_STATE=96
#      - ORDER_SCHEDULER_NOTIFY_DELIVERY_PENDING_STATE=48
#      - ORDER_SCHEDULER_DELIVERED_STATE=144
#      - ORDER_SCHEDULER_RETURN_SHIPPED_STATE=72
#      - ORDER_SCHEDULER_RETURN_REQUEST_PENDING_STATE=72
#      - ORDER_SCHEDULER_RETURN_SHIPMENT_PENDING_STATE=96
#      - ORDER_SCHEDULER_RETURN_DELIVERED_STATE=96
#      - ORDER_PAYMENT_CALLBACK_URL_SUCCESS=http://staging.faza.io/callback-success?orderId=
#      - ORDER_PAYMENT_CALLBACK_URL_FAIL=http://staging.faza.io/callback-failed?orderId=
#      - PROMETHEUS_PORT=9100
#      - NOTIFICATION_SMS_TEMPLATES=/app/notification/sms/smsTemplate.txt
#      - EMAIL_TMP_NOTIFY_SELLER_FOR_NEW_ORDER=NotifySellerForNewOrder.html
#      - PAYMENT_GATEWAY_ADDRESS=
#      - PAYMENT_GATEWAY_PORT=3010
#      - PAYMENT_SERVICE_MOCK_ENABLED=true
#      - STOCK_SERVICE_ADDRESS=
#      - STOCK_SERVICE_PORT=9098
#      - STOCK_SERVICE_MOCK_ENABLED=true
#      - USER_SERVICE_ADDRESS=userservice
#      - USER_SERVICE_PORT=9096
#      - NOTIFY_SERVICE_ADDRESS=notifyservice
#      - NOTIFY_SERVICE_PORT=9099
#      - NOTIFY_SERVICE_TIMEOUT=30
#      - NOTIFY_SERVICE_SELLER_ENABLED=true
#      - NOTIFY_SERVICE_BUYER_ENABLED=true
#
#    depends_on:
#      - mongo
#      - userservice

#  paymentservice:
##    image: registry.faza.io/payment-transfer/payment-transfer:staging
#    image: payment-trasfer-service:latest
#    restart: unless-stopped
#    ports:
#      - 9793:9793
#    security_opt:
#      - seccomp:unconfined
#    environment:
#      - PORT=9793
#      - MONGO_URL=mongodb://mongo1:52301,mongo2:52302,mongo3:52303
#      - DB_NAME=paymentTransfer
#      - BANK_MELLI_CLIENT_KEY=
#      - BANK_MELLI_CLIENT_SECRET=
#      - BANK_MELLI_ACCOUNT_ID=0225823144002
#    depends_on:
#      - mongo1
#      - mongo2
#      - mongo3
#
#  mongo1:
#    image: registry.faza.io/mongo:4.2.2
#    container_name: mongo1
#    restart: unless-stopped
#    networks:
#      - payment-transfer
#    command: /usr/bin/mongod --bind_ip_all --replSet=rs0 --port 52301
#    ports:
#      - 52301:52301
#
#  mongo2:
#    image: registry.faza.io/mongo:4.2.2
#    restart: unless-stopped
#    container_name: mongo2
#    networks:
#      - payment-transfer
#    command: /usr/bin/mongod --bind_ip_all --replSet=rs0 --port 52302
#    ports:
#      - 52302:5230
#
#  mongo3:
#    image: registry.faza.io/mongo:4.2.2
#    restart: unless-stopped
#    container_name: mongo3
#    networks:
#      - payment-transfer
#    command: /usr/bin/mongod --bind_ip_all --replSet=rs0 --port 52303
#    ports:
#      - 52303:52303

  redis:
    image: registry.faza.io/redis:5.0
    ports:
      - 50079:6379

  mongo:
    image: registry.faza.io/mongo:4.2.2
    ports:
      - 27017:27017

  mongo-express:
    image: registry.faza.io/mongo-express:0.49
    ports:
      - 8081:8081

#  mongo1:
#    image: registry.faza.io/mongo:4.2.2
#    restart: unless-stopped
#    container_name: mongo1
#    command: /usr/bin/mongod --bind_ip_all --replSet=rs0 --port 52301
#    ports:
#      - 52301:52301
#
#  mongo2:
#    image: registry.faza.io/mongo:4.2.2
#    restart: unless-stopped
#    container_name: mongo2
#    command: /usr/bin/mongod --bind_ip_all --replSet=rs0 --port 52302
#    ports:
#      - 52302:52302
#
#  mongo3:
#    image: registry.faza.io/mongo:4.2.2
#    restart: unless-stopped
#    container_name: mongo3
#    command: /usr/bin/mongod --bind_ip_all --replSet=rs0 --port 52303
#    ports:
#      - 52303:52303
